apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fiskekartan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fiskekartan.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
  MINIO_ENDPOINT: {{ .Values.minioEndpoint | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minioSecretKey | quote }}
