apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiskekartan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fiskekartan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fiskekartan.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
