import 'package:flutter/services.dart';
import 'package:maplibre_gl/maplibre_gl.dart';

import '../api/api_client.dart';
import '../theme/app_theme.dart';

// Same viewport rules as web/src/lib/Map.svelte: start over Sweden, and keep
// the camera inside the bbox sweden.pmtiles was extracted with — there's no
// basemap data outside it.
const swedenCenter = LatLng(62.5, 15.0);
const swedenMinZoom = 6.0;
final swedenBounds = LatLngBounds(
  southwest: const LatLng(55.0, 10.5),
  northeast: const LatLng(69.5, 24.5),
);

/// Close enough to see the shoreline around you.
const closeUpZoom = 13.0;

final _styles = <MapTheme, Future<String>>{};

/// The basemap style for [theme], loaded once and shared by every map in the
/// app. assets/map/style_*.json are generated by tool/generate_map_style.mjs;
/// the tiles come from the same backend route the web app uses.
Future<String> mapStyleFor(MapTheme theme) => _styles[theme] ??= rootBundle
    .loadString('assets/map/style_${theme.name}.json')
    .then(
      (style) =>
          style.replaceFirst('{TILES_URL}', apiUrl('/tiles/sweden.pmtiles')),
    );
